language: java
before_script:
  - chmod +x gradlew
jobs:
 include:
  - stage: "Initial Assemble"
    language: java
    script:
     - ./gradlew assemble
  - stage: "Style Checks"
    language: java
    script:
     - ./gradlew checkstyleMain
     - ./gradlew checkstyleTest
  - stage: "Tests"
    language: java
    script:
     - ./gradlew test
  - stage: "Static Analysis"
    language: java
    script:
     - ./gradlew pmdMain
     - ./gradlew pmdTest
  - stage: "Test Coverage"
    language: java
    script:
     - ./gradlew jacocoTestReport
     - ./gradlew jacocoTestCoverageVerification