language: java
before_script:
  - chmod +x gradlew
jobs:
 include:
  - stage: "Initial assemble"
    script:
     - ./gradlew assemble
  - stage: "Style Checks"
    script:
      - ./gradlew checkstyleMain
      - ./gradlew checkstyleTest